# Site settings
title: Scott's Git practice site.
author:
  name: Scott
  email: ScottHenshaw86@gmail.com

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
