# Site settings
title: Scott
author:
  name: Scott
  email: ScottHenshaw86@gmail.com
description: "Great site to practive with Git."

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
